before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: go-wallpaper
    goos:
      - windows
    goarch:
      - amd64
    goarm:
      - '6'
    gomips:
      - hardfloat
    targets:
      - windows_amd64
    dir: .
    main: .
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
        -X main.builtBy=goreleaser
    binary: go-wallpaper
    env:
      - CGO_ENABLED=0
    lang: go
    gobinary: go
archives:
  - id: default
    builds:
      - go-wallpaper
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
      }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    replacements:
      amd64: x86_64
    format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
    allow_different_binary_count: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
env_files:
  github_token: ./.env
